import fs from 'node:fs/promises'
import mupdf from 'mupdf'
import { expect, test, type Page } from '@playwright/test'

function blankPdf() {
  const doc = new mupdf.PDFDocument()
  try {
    for (let i = 0; i < 3; i++) { const ref = doc.addPage([0, 0, 400, 400], 0, {}, ''); try { doc.insertPage(-1, ref) } finally { ref.destroy() } }
    const bytes = doc.saveToBuffer('compress'); try { return [...bytes.asUint8Array()] } finally { bytes.destroy() }
  } finally { doc.destroy() }
}
async function open(page: Page) {
  await page.goto('/karu-pdf/?test=1&workers=2&warm=0')
  await page.waitForFunction(() => !!window.__karu)
  await page.evaluate(bytes => window.__karu!.openBytes(bytes, '器具試験.pdf'), blankPdf())
  await page.evaluate(() => window.__karu!.setZoom(1))
  await page.getByRole('tab', { name: '器具', exact: true }).click()
  await expect(page.getByRole('button', { name: '器具を追加', exact: true })).toBeEnabled()
}
async function clickPoint(page: Page, pageIndex: number, x: number, y: number, modifiers?: Array<'Shift'>) {
  const layer = page.getByTestId(`annotation-layer-${pageIndex}`)
  const position = await layer.evaluate((el, p) => { const svg = el as SVGSVGElement, box = svg.getBoundingClientRect(); return { x: p.x * box.width / svg.viewBox.baseVal.width, y: p.y * box.height / svg.viewBox.baseVal.height } }, { x, y })
  await layer.click({ position, modifiers })
}
async function select(page: Page, name: string) {
  await page.getByRole('button', { name, exact: true }).click()
  await expect(page.getByRole('button', { name: '個数カウント', exact: true })).toHaveAttribute('aria-pressed', 'true')
}

test('presets count across pages, visibility excludes hit testing, and quantity CSV includes zero fixtures', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: '見本から追加', exact: true }).click()
  await page.getByRole('button', { name: '選んだ器具を追加', exact: true }).click()
  await select(page, 'DL ダウンライト'); await clickPoint(page, 0, 80, 90); await clickPoint(page, 0, 130, 90)
  await expect(page.getByTestId('fixture-panel')).toContainText('表示中の図面（p.1）: 2個 ／ 全図面: 2個')
  const firstId = await page.evaluate(() => { const a = window.__karu!.getEditableAnnotations(0).find(a => a.count)!; return a.count!.version === 2 ? a.count!.fixtureId : '' })
  await select(page, 'C2 コンセント（2口）'); await clickPoint(page, 0, 200, 90)
  await page.evaluate(() => window.__karu!.scrollToPage(1))
  await expect(page.getByTestId('fixture-panel')).toContainText('表示中の図面（p.2）: 0個 ／ 全図面: 1個')
  await clickPoint(page, 1, 80, 100)
  await expect(page.getByTestId('fixture-panel')).toContainText('表示中の図面（p.2）: 1個 ／ 全図面: 2個')
  await page.evaluate(() => window.__karu!.scrollToPage(0))
  await page.getByRole('button', { name: 'DL ダウンライトの表示切替', exact: true }).click()
  await page.getByRole('button', { name: '選択', exact: true }).click()
  await clickPoint(page, 0, 80, 90)
  await expect(page.getByTestId('annotation-layer-0').locator('.annotation-selection')).toHaveCount(0)
  await page.getByRole('button', { name: 'すべて表示', exact: true }).click()
  await clickPoint(page, 0, 80, 90)
  await expect(page.getByTestId('annotation-layer-0').locator('.annotation-selection')).toHaveCount(1)
  await page.getByLabel('器具を変更', { exact: true }).selectOption({ label: 'C2 コンセント（2口）' })
  await expect(page.getByTestId('fixture-panel')).toContainText('表示中の図面（p.1）: 2個 ／ 全図面: 3個')
  await page.getByRole('button', { name: '元に戻す', exact: true }).click()
  expect(await page.evaluate(id => window.__karu!.getEditableAnnotations(0).filter(a => a.count?.version === 2 && a.count.fixtureId === id).length, firstId)).toBe(2)
  await select(page, 'DL ダウンライト')
  await page.getByLabel('選択中の器具だけ表示', { exact: true }).check()
  await expect(page.getByTestId('annotation-layer-0').locator('g[data-annotation-id]')).toHaveCount(2)
  await page.getByRole('button', { name: 'すべて表示', exact: true }).click()
  await expect(page.getByLabel('選択中の器具だけ表示', { exact: true })).not.toBeChecked()
  await expect(page.getByTestId('annotation-layer-0').locator('g[data-annotation-id]')).toHaveCount(3)
  await page.evaluate(() => { Object.defineProperty(window, 'showSaveFilePicker', { value: undefined, configurable: true }) })
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name: '個数をCSVに書き出す', exact: true }).click()
  const download = await pending
  expect(download.suggestedFilename()).toBe('器具試験_個数.csv')
  const csv = await fs.readFile((await download.path())!, 'utf8')
  expect(csv).toContain('分類,略号,器具名称,表示中の図面（p.1）,全図面の合計,p.1,p.2\r\n')
  expect(csv).toContain('照明器具,DL,ダウンライト,2,2,2,0\r\n')
  expect(csv).toContain('コンセント,C2,コンセント（2口）,1,2,1,1\r\n')
  expect(csv).toContain('照明器具,BL,ベースライト（直付）,0,0,0,0\r\n')
})

test('custom style, duplication, bulk editing, multiple reassignment, undo, and save/reopen', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: '器具を追加', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '器具を追加', exact: true })
  await dialog.getByLabel('器具名称', { exact: true }).fill('試験器具'); await dialog.getByLabel('略号', { exact: true }).fill('T')
  await dialog.getByRole('button', { name: '形 逆三角', exact: true }).click()
  await dialog.getByRole('button', { name: '塗り 半分塗り', exact: true }).click()
  await dialog.getByRole('button', { name: '色 #FFF04D', exact: true }).click()
  await dialog.getByRole('button', { name: '追加する', exact: true }).click()
  await select(page, 'T 試験器具'); await clickPoint(page, 0, 80, 90); await clickPoint(page, 0, 140, 90)
  const layer = page.getByTestId('annotation-layer-0')
  await expect(layer.locator('[data-count-shape="invertedTriangle"][data-count-fill="half"]')).toHaveCount(2)
  await page.getByRole('button', { name: '複製', exact: true }).click()
  const copy = page.getByRole('dialog', { name: '器具を追加', exact: true })
  await expect(copy.getByLabel('器具名称', { exact: true })).toHaveValue('試験器具 のコピー')
  await copy.getByLabel('略号', { exact: true }).fill('U'); await copy.getByRole('button', { name: '形 四角', exact: true }).click()
  await copy.getByRole('button', { name: '追加する', exact: true }).click()
  await select(page, 'T 試験器具'); await page.getByRole('button', { name: '編集', exact: true }).click()
  const edit = page.getByRole('dialog', { name: '器具を編集', exact: true })
  await edit.getByRole('button', { name: '形 星', exact: true }).click(); await edit.getByRole('button', { name: '変更する', exact: true }).click()
  await expect(layer.locator('[data-count-shape="star"]')).toHaveCount(2)
  await page.getByRole('button', { name: '選択', exact: true }).click()
  await clickPoint(page, 0, 80, 90); await clickPoint(page, 0, 140, 90, ['Shift'])
  await page.getByLabel('器具を変更', { exact: true }).selectOption({ label: 'U 試験器具 のコピー' })
  await expect(layer.locator('[data-count-shape="square"]')).toHaveCount(2)
  await page.getByRole('button', { name: '元に戻す', exact: true }).click()
  await expect(layer.locator('[data-count-shape="star"]')).toHaveCount(2)
  const saved = await page.evaluate(async () => [...(await window.__karu!.saveToBytes())!])
  await page.evaluate(bytes => window.__karu!.openBytes(bytes, '保存後.pdf'), saved)
  await page.getByRole('tab', { name: '器具', exact: true }).click(); await select(page, 'T 試験器具')
  await expect(page.getByTestId('fixture-panel')).toContainText('全図面: 2個')
  await expect(page.getByRole('button', { name: 'U 試験器具 のコピー', exact: true })).toBeVisible()
  await expect(page.getByTestId('annotation-layer-0').locator('[data-count-shape="star"]')).toHaveCount(2)
})

test('imports another open PDF without duplicate names/codes and keeps fixture deletion undoable', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: '見本から追加', exact: true }).click()
  await page.getByLabel('見本の分野', { exact: true }).selectOption('建築')
  await page.getByRole('button', { name: '選んだ器具を追加', exact: true }).click()
  await select(page, 'DS 片開き戸'); await clickPoint(page, 0, 90, 90)
  await page.getByRole('button', { name: '削除', exact: true }).click({ trial: true })
  page.once('dialog', async d => { expect(d.message()).toContain('この器具の印 1 個も削除します'); await d.accept() })
  await page.getByRole('button', { name: '削除', exact: true }).click()
  await expect(page.getByRole('button', { name: 'DS 片開き戸', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '元に戻す', exact: true }).click()
  await select(page, 'DS 片開き戸'); await expect(page.getByTestId('fixture-panel')).toContainText('全図面: 1個')
  await page.evaluate(bytes => window.__karu!.openBytes(bytes, '読込先.pdf'), blankPdf())
  await page.getByRole('tab', { name: '器具', exact: true }).click()
  await page.getByRole('button', { name: '他のPDFから読み込む', exact: true }).click()
  await page.getByRole('button', { name: '選んだ器具を追加', exact: true }).click()
  await select(page, 'DS 片開き戸'); await expect(page.getByTestId('fixture-panel')).toContainText('全図面: 0個')
  const first = await page.getByTestId('fixture-panel').locator('li[data-fixture-id]').count()
  await page.getByRole('button', { name: '他のPDFから読み込む', exact: true }).click()
  await page.getByRole('button', { name: '選んだ器具を追加', exact: true }).click()
  await expect(page.getByTestId('fixture-panel').locator('li[data-fixture-id]')).toHaveCount(first)
})

test('requires a fixture and warns for same-fixture clicks within 3mm without dropping the new mark', async ({ page }) => {
  await open(page)
  await page.getByRole('button', { name: '計測▼', exact: true }).click()
  await page.getByRole('menuitemcheckbox', { name: '個数カウント', exact: true }).click()
  await clickPoint(page, 0, 100, 100)
  expect(await page.evaluate(() => window.__karu!.getEditableAnnotations(0).filter(a => a.count).length)).toBe(0)
  await expect(page.getByRole('status')).toContainText('器具リストで器具を選んでください')
  await page.getByRole('button', { name: '見本から追加', exact: true }).click()
  await page.getByRole('button', { name: '選んだ器具を追加', exact: true }).click()
  await select(page, 'DL ダウンライト'); await clickPoint(page, 0, 100, 100); await clickPoint(page, 0, 103, 100)
  await expect(page.getByRole('status')).toContainText('近くに同じ器具の印があります')
  await expect(page.getByTestId('fixture-panel')).toContainText('全図面: 2個')
})
