import { expect, test, type Page } from '@playwright/test'
import { makeDrawingInfoPdf } from '../tests/drawingInfoFixtures'

async function open(page: Page) {
  await page.goto('/karu-pdf/?test=1&workers=2&warm=0')
  await page.waitForFunction(() => Boolean(window.__karu))
  await page.evaluate(data => window.__karu!.openBytes(data, '図面情報試験.pdf'), [...await makeDrawingInfoPdf()])
  await expect(page.getByTestId('annotation-layer-0')).toBeVisible()
}
async function scanned(page: Page) {
  await expect(page.getByTestId('drawing-scan-status')).toContainText('読み取りました')
  await expect.poll(() => page.evaluate(() => window.__karu!.getDrawingInfos().every(i => i?.scanned))).toBe(true)
}
async function rename(page: Page, name: string) {
  await page.getByTestId('status-drawing-info').click()
  const dialog = page.getByRole('dialog', { name: '図面番号・図面名称を変更', exact: true })
  await dialog.getByLabel('図面名称', { exact: true }).fill(name)
  await dialog.getByRole('button', { name: '決定', exact: true }).click()
}
test('自動読取・手動変更とUndo・再読取・保存復元・整理のページ対応', async ({ page }) => {
  await open(page)
  expect(await page.evaluate(() => window.__karu!.getDrawingScanMetrics().totalMs)).toBe(0)
  await page.getByRole('tab', { name: '数量', exact: true }).click(); await scanned(page)
  await expect(page.getByTestId('status-drawing-info')).toContainText('E-101 1階 電灯設備平面図')
  expect(await page.evaluate(() => window.__karu!.listTabs()[0].dirty)).toBe(false)
  await page.getByRole('tab', { name: 'ページ', exact: true }).click()
  await expect(page.getByTestId('thumbnail-0')).toContainText('E-101')
  await expect(page.getByTestId('thumbnail-0')).toHaveAttribute('title', 'E-101 1階 電灯設備平面図')
  await page.getByTestId('thumbnail-1').click()
  await expect(page.getByTestId('status-drawing-info')).toContainText('E-102')
  await rename(page, '手動の2階図面')
  await page.keyboard.press('Control+z')
  await expect(page.getByTestId('status-drawing-info')).toContainText('2階 電灯設備平面図')
  await rename(page, '手動の2階図面')
  await page.getByRole('tab', { name: '数量', exact: true }).click()
  await page.getByRole('button', { name: '図面番号・図面名称を読み直す', exact: true }).click(); await scanned(page)
  await expect(page.getByTestId('status-drawing-info')).toContainText('手動の2階図面')
  const saved = await page.evaluate(async () => [...(await window.__karu!.saveToBytes())!])
  await page.evaluate(async data => { const id = window.__karu!.listTabs()[0].docId; await window.__karu!.closeTab(id); await window.__karu!.openBytes(data, '保存した図面.pdf') }, saved)
  await page.getByRole('tab', { name: '数量', exact: true }).click()
  expect(await page.evaluate(() => window.__karu!.getDrawingScanMetrics().totalMs)).toBe(0)
  expect(await page.evaluate(() => window.__karu!.getDrawingInfos()[1])).toMatchObject({ number: 'E-102', name: '手動の2階図面', nameManual: true, scanned: true })
  await page.evaluate(async () => {
    await window.__karu!.openOrganize()
    const draft = window.__karu!.organizeDraft()!, cards = draft.getCards().slice()
    draft.move([cards[1].id], 0)
    await window.__karu!.applyOrganize()
  })
  expect(await page.evaluate(() => window.__karu!.getDrawingInfos().map(i => i?.number))).toEqual(['E-102', 'E-101', 'E-103'])
  await expect(page.getByTestId('status-drawing-info')).toContainText('E-102')
  await expect.poll(() => page.evaluate(() => window.__karu!.isSharp()), { timeout: 60000 }).toBe(true)
  await page.getByRole('tab', { name: 'ページ', exact: true }).click()
  await page.screenshot({ path: 'work/spec05b/drawing-info-ui.png' })
})
test('通常閲覧と自動読取のみは保存確認なしで閉じられる', async ({ page }) => {
  let prompts = 0
  page.on('dialog', async dialog => { prompts++; await dialog.dismiss() })
  await open(page)
  expect(await page.evaluate(() => window.__karu!.getDrawingInfos())).toEqual([null, null, null])
  await page.evaluate(async () => window.__karu!.closeTab(window.__karu!.listTabs()[0].docId))
  expect(prompts).toBe(0); expect(await page.evaluate(() => window.__karu!.listTabs().length)).toBe(0)
  await page.evaluate(data => window.__karu!.openBytes(data, '自動読取のみ.pdf'), [...await makeDrawingInfoPdf()])
  await page.getByRole('tab', { name: '数量', exact: true }).click(); await scanned(page)
  await page.evaluate(async () => window.__karu!.closeTab(window.__karu!.listTabs()[0].docId))
  expect(prompts).toBe(0); expect(await page.evaluate(() => window.__karu!.listTabs().length)).toBe(0)
})
test('右クリック編集と自動に戻す・手動空欄', async ({ page }) => {
  await open(page); await page.getByRole('tab', { name: '数量', exact: true }).click(); await scanned(page)
  await rename(page, '')
  await page.getByRole('button', { name: '図面番号・図面名称を読み直す', exact: true }).click(); await scanned(page)
  expect(await page.evaluate(() => window.__karu!.getDrawingInfos()[0]?.name)).toBeUndefined()
  await page.getByRole('tab', { name: 'ページ', exact: true }).click()
  await page.getByTestId('thumbnail-0').click({ button: 'right' })
  await page.getByRole('menuitem', { name: '図面番号・図面名称を変更…', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '図面番号・図面名称を変更', exact: true })
  await dialog.getByRole('button', { name: '図面名称を自動に戻す', exact: true }).click()
  await dialog.getByRole('button', { name: '決定', exact: true }).click()
  await expect(page.getByTestId('status-drawing-info')).toContainText('1階 電灯設備平面図')
  expect(await page.evaluate(() => window.__karu!.getDrawingInfos()[0]?.nameManual)).toBe(false)
})
