import { expect, test, type Page } from '@playwright/test'
import mupdf from 'mupdf'
import { listAnnotations } from '../src/core/annotations'
import { readCountFixtures } from '../src/core/countFixtures'
import { writePageScale } from '../src/core/measure'

// All PDFs and saved bytes remain in memory; this suite writes no fixture files.
function blankPdf() {
  const doc = new mupdf.PDFDocument()
  try {
    const ref = doc.addPage([0, 0, 500, 500], 0, {}, '')
    try { doc.insertPage(-1, ref) } finally { ref.destroy() }
    const page = doc.loadPage(0)
    try { writePageScale(doc, page, { denominator: 100, paper: 'PDF', source: 'ratio', mmPerPoint: 25.4 / 72 * 100, unit: 'm', decimals: 2 }) } finally { page.destroy() }
    const buffer = doc.saveToBuffer('compress')
    try { return [...buffer.asUint8Array()] } finally { buffer.destroy() }
  } finally { doc.destroy() }
}
const panel = (p: Page) => p.getByTestId('fixture-panel')
const format = (p: Page) => p.getByTestId('format-panel')
const picker = (p: Page) => p.getByRole('dialog', { name: '線要素を追加', exact: true })
const row = (p: Page, code: string, name: string) => panel(p).getByRole('button', { name: code + ' ' + name, exact: true })
async function point(page: Page, x: number, y: number) {
  const layer = page.getByTestId('annotation-layer-0')
  const position = await layer.evaluate((element, p) => { const svg = element as SVGSVGElement, rect = svg.getBoundingClientRect(); return { x: p.x * rect.width / svg.viewBox.baseVal.width, y: p.y * rect.height / svg.viewBox.baseVal.height } }, { x, y })
  await layer.click({ position })
}
async function draw(page: Page, y: number) { await point(page, 100, y); await point(page, 172, y); await page.keyboard.press('Enter') }
async function selectRoute(page: Page, y = 220) { await page.getByRole('button', { name: '選択', exact: true }).click(); await point(page, 136, y); await expect(format(page).getByText('経路構成', { exact: true })).toBeVisible() }
async function open(page: Page, bytes = blankPdf()) {
  await page.waitForFunction(() => !!window.__karu)
  await page.evaluate(b => window.__karu!.openBytes(b, '経路構成.pdf'), bytes)
  await page.evaluate(() => window.__karu!.setZoom(1))
  await page.getByRole('tab', { name: '数量', exact: true }).click()
  await expect(panel(page).getByRole('button', { name: '項目を追加', exact: true })).toBeEnabled()
}
async function addFixture(page: Page, code: string, spec: string, name: string) {
  await panel(page).getByRole('button', { name: '項目を追加', exact: true }).click()
  const dialog = page.getByRole('dialog', { name: '項目を追加', exact: true })
  await dialog.getByLabel('略号', { exact: true }).fill(code)
  await dialog.getByLabel('規格', { exact: true }).fill(spec)
  await dialog.getByLabel('名称', { exact: true }).fill(name)
  await dialog.getByRole('radio', { name: '長さ', exact: true }).check()
  await dialog.getByRole('button', { name: '追加する', exact: true }).click()
}
async function setup(page: Page) {
  await page.setViewportSize({ width: 1600, height: 1000 })
  await page.goto('/karu-pdf/?test=1&workers=2&warm=0')
  await open(page)
  await addFixture(page, 'EM-CE', '5.5sq-3C', 'ケーブル')
  await addFixture(page, 'IV', '5.5sq', '接地線')
  await addFixture(page, 'PF22', '', '電線管')
  await row(page, 'EM-CE 5.5sq-3C', 'ケーブル').click()
  await draw(page, 220)
}
async function addLine(page: Page, query: string, code: string, master = false) {
  await format(page).getByRole('button', { name: '線要素を追加', exact: true }).click()
  await expect(picker(page).getByLabel('線要素を検索', { exact: true })).toBeFocused()
  await picker(page).getByLabel('線要素を検索', { exact: true }).fill(query)
  const section = picker(page).locator('section').filter({ has: page.getByRole('heading', { name: master ? '標準マスタ' : 'この PDF の項目', exact: true }) })
  await section.getByRole('button', { name: code, exact: true }).click()
  await expect(picker(page)).toHaveCount(0)
}
const routes = (p: Page) => p.evaluate(() => window.__karu!.getEditableAnnotations(0).filter(a => a.quantity).map(a => a.quantity!))
async function saveBytes(page: Page) { return page.evaluate(async () => [...(await window.__karu!.saveToBytes())!]) }

test('経路構成、1クリック追加、原子的Undo、条数、主の変更、図面の札と保存', async ({ page }) => {
  await setup(page)
  await expect(format(page).getByText('経路構成', { exact: true })).toBeVisible()
  await expect(format(page).getByText('1種類・1条', { exact: true })).toBeVisible()
  await expect(format(page).locator('.route-item-main')).toContainText('EM-CE 5.5sq-3C')
  await expect(format(page).locator('.route-item')).toHaveCount(1)
  await expect(page.locator('.route-composition-badge')).toHaveCount(0)

  await addLine(page, 'iv', 'IV 5.5sq')
  await expect(format(page).locator('.route-item')).toHaveCount(2)
  await expect(format(page).getByText('2種類・2条', { exact: true })).toBeVisible()
  await expect(format(page).locator('.route-item-added')).toContainText('IV 5.5sq')
  await expect(format(page).getByRole('status')).toContainText('IV 5.5sq を足しました')
  await expect(page.locator('.pickup-route-row .route-item-added')).toContainText('IV 5.5sq')
  await format(page).getByRole('button', { name: '線要素を追加', exact: true }).click()
  await picker(page).getByLabel('線要素を検索', { exact: true }).fill('iv')
  const added = picker(page).getByRole('button', { name: 'IV 5.5sq 追加済み', exact: true })
  await expect(added.first()).toBeDisabled()
  await page.keyboard.press('Escape'); await expect(picker(page)).toHaveCount(0)
  await expect(format(page).getByText('経路構成', { exact: true })).toBeVisible()

  await addLine(page, 'pf2', 'PF28', true)
  await expect(format(page).locator('.route-item')).toHaveCount(3)
  await expect(panel(page).locator('.fixture-row-code').filter({ hasText: /^PF28\s*$/ })).toHaveCount(1)
  await page.keyboard.press('Control+z')
  await expect(panel(page).locator('.fixture-row-code').filter({ hasText: /^PF28\s*$/ })).toHaveCount(0)
  expect((await routes(page))[0].extra).toHaveLength(1)
  await page.keyboard.press('Control+y')
  await expect(panel(page).locator('.fixture-row-code').filter({ hasText: /^PF28\s*$/ })).toHaveCount(1)
  expect((await routes(page))[0].extra).toHaveLength(2)
  await selectRoute(page)

  const total = row(page, 'EM-CE 5.5sq-3C', 'ケーブル').locator('..').locator('.fixture-row-count').last()
  await expect(total).toHaveText('2.54')
  await format(page).getByRole('button', { name: 'EM-CE 5.5sq-3Cの条数を増やす', exact: true }).click()
  await expect(format(page).getByLabel('EM-CE 5.5sq-3Cの条数', { exact: true })).toHaveValue('2')
  await expect(format(page).getByText('3種類・4条', { exact: true })).toBeVisible()
  await expect(total).toHaveText('5.08')
  await expect(format(page).getByRole('status')).toContainText('EM-CE 5.5sq-3C を 2条にしました')
  await format(page).getByRole('button', { name: 'EM-CE 5.5sq-3Cの条数を減らす', exact: true }).click()
  await expect(format(page).getByRole('button', { name: 'EM-CE 5.5sq-3Cの条数を減らす', exact: true })).toBeDisabled()
  await expect(page.locator('.pickup-route-row .pickup-route-chip')).toHaveCount(3)
  await page.getByRole('button', { name: '拾いバーのEM-CE 5.5sq-3Cの条数を増やす', exact: true }).click()
  await expect(format(page).getByLabel('EM-CE 5.5sq-3Cの条数', { exact: true })).toHaveValue('2')
  await expect(page.locator('.route-composition-badge text')).toHaveText('3')
  await expect(page.locator('.route-composition-badge title')).toContainText('EM-CE 5.5sq-3C×2、IV 5.5sq、PF28')
  await expect(page.locator('.route-composition-badge')).toHaveAttribute('pointer-events', 'none')
  await panel(page).getByRole('button', { name: '管理', exact: true }).click()
  await panel(page).getByLabel('図面に長さ・面積・体積の数値を表示', { exact: true }).uncheck()
  await expect(page.locator('.measurement-label')).toHaveCount(0)
  await expect(page.locator('.route-composition-badge text')).toHaveText('3')
  await panel(page).getByLabel('図面に長さ・面積・体積の数値を表示', { exact: true }).check()
  await format(page).getByRole('button', { name: 'PF28を外す', exact: true }).click()
  await expect(format(page).getByRole('status')).toContainText('PF28 を外しました（Ctrl+Z で戻せます）')
  await format(page).getByRole('button', { name: 'IV 5.5sqを外す', exact: true }).click()
  await expect(page.locator('.route-composition-badge')).toHaveCount(0)
  await page.keyboard.press('Control+z'); await page.keyboard.press('Control+z'); await selectRoute(page)

  const originalColor = await page.locator('.measurement-shape > polyline').getAttribute('stroke')
  const ivColor = await format(page).getByRole('button', { name: 'IV 5.5sqを主にする', exact: true }).locator('..').locator('.fixture-swatch path').evaluate(el => getComputedStyle(el).stroke)
  await format(page).getByRole('button', { name: 'IV 5.5sqを主にする', exact: true }).click()
  await expect(format(page).locator('.route-item-main')).toContainText('IV 5.5sq')
  await expect.poll(() => page.locator('.measurement-shape > polyline').evaluate(el => getComputedStyle(el).stroke)).toBe(ivColor)
  await page.keyboard.press('Control+z'); await selectRoute(page)
  await expect(format(page).locator('.route-item-main')).toContainText('EM-CE 5.5sq-3C')
  await expect(page.locator('.measurement-shape > polyline')).toHaveAttribute('stroke', originalColor!)
  await format(page).getByLabel('PF28の範囲', { exact: true }).selectOption('rise')
  await format(page).getByLabel('立上り・立下り', { exact: true }).fill('3')
  await format(page).getByLabel('立上り・立下り', { exact: true }).press('Enter')
  const before = (await routes(page))[0], bytes = await saveBytes(page), doc = new mupdf.PDFDocument(new Uint8Array(bytes))
  try {
    const saved = listAnnotations(doc, 0)[0].quantity!
    expect(saved).toMatchObject({ itemId: before.itemId, count: 2, extra: JSON.parse(JSON.stringify(before.extra)) })
    expect(readCountFixtures(doc).some(f => f.code === 'PF28')).toBe(true)
  } finally { doc.destroy() }
  await open(page, bytes); await selectRoute(page)
  expect((await routes(page))[0]).toEqual(before)
  await expect(format(page).locator('.route-item')).toHaveCount(3)
  await expect(format(page).getByLabel('PF28の範囲', { exact: true })).toHaveValue('rise')
})

test('よく使う構成を別の経路と新しい経路に使い、解除・再読込・名前変更・削除', async ({ page }) => {
  await setup(page)
  await addLine(page, 'iv', 'IV 5.5sq')
  await addLine(page, 'pf2', 'PF28', true)
  await format(page).getByLabel('EM-CE 5.5sq-3Cの条数', { exact: true }).fill('2')
  await format(page).getByLabel('EM-CE 5.5sq-3Cの条数', { exact: true }).press('Enter')
  await format(page).getByLabel('PF28の範囲', { exact: true }).selectOption('rise')
  const composition = (await routes(page))[0]
  const itemsOf = (q: typeof composition) => ({ itemId: q.itemId, count: q.count ?? 1, scope: q.scope ?? 'all', extra: q.extra })
  await format(page).getByRole('button', { name: 'よく使う構成', exact: true }).click()
  const sets = page.getByRole('dialog', { name: 'よく使う構成', exact: true })
  await expect(sets.getByText('この経路の構成を登録', { exact: true })).toBeVisible()
  await sets.getByLabel('構成の名前', { exact: true }).fill('幹線A')
  await sets.getByRole('button', { name: '登録', exact: true }).click()
  await expect(sets.getByRole('button', { name: '幹線A', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await row(page, 'EM-CE 5.5sq-3C', 'ケーブル').click(); await draw(page, 300)
  await expect(format(page).locator('.route-item')).toHaveCount(1)
  await format(page).getByRole('button', { name: 'よく使う構成', exact: true }).click()
  await sets.getByRole('button', { name: '幹線A', exact: true }).click()
  expect(itemsOf((await routes(page))[1])).toEqual(itemsOf(composition))
  await page.keyboard.press('Control+z'); expect((await routes(page))[1].extra).toBeUndefined()
  await page.keyboard.press('Control+y'); expect(itemsOf((await routes(page))[1])).toEqual(itemsOf(composition))
  await panel(page).getByRole('button', { name: '拾う', exact: true }).click()
  await panel(page).getByRole('region', { name: 'よく使う構成', exact: true }).getByRole('button', { name: '幹線A', exact: true }).click()
  await expect(page.locator('.pickup-template')).toContainText('構成: 幹線A')
  await draw(page, 380)
  expect(itemsOf((await routes(page))[2])).toEqual(itemsOf(composition))
  await expect(format(page).locator('.route-item')).toHaveCount(3)
  await page.getByRole('button', { name: '構成を外す', exact: true }).click()
  await expect(page.locator('.pickup-template')).toHaveCount(0)
  await draw(page, 440); expect((await routes(page))[3].extra).toBeUndefined(); expect((await routes(page))[3].count ?? 1).toBe(1)

  const bytes = await saveBytes(page)
  await page.reload(); await open(page, bytes)
  await panel(page).getByRole('button', { name: '拾う', exact: true }).click()
  await expect(panel(page).getByRole('region', { name: 'よく使う構成', exact: true }).getByRole('button', { name: '幹線A', exact: true })).toBeVisible()
  await selectRoute(page, 220)
  await format(page).getByRole('button', { name: 'よく使う構成', exact: true }).click()
  await sets.getByRole('button', { name: '幹線Aの名前を変える', exact: true }).click()
  await sets.getByLabel('構成の新しい名前', { exact: true }).fill('幹線B')
  await sets.getByRole('button', { name: '保存', exact: true }).click()
  await expect(sets.getByRole('button', { name: '幹線B', exact: true })).toBeVisible()
  await sets.getByRole('button', { name: '幹線Bを削除', exact: true }).click()
  await expect(sets.getByRole('button', { name: '幹線B', exact: true })).toHaveCount(0)
  await expect(panel(page).getByRole('region', { name: 'よく使う構成', exact: true })).toHaveCount(0)
})

test('追加画面のキーボードと外側クリック、条数入力の確定・上限・ホイール', async ({ page }) => {
  await setup(page)
  await format(page).getByRole('button', { name: '線要素を追加', exact: true }).click()
  await picker(page).getByLabel('線要素を検索', { exact: true }).fill('接地線')
  await picker(page).getByLabel('線要素を検索', { exact: true }).press('ArrowDown')
  await picker(page).getByLabel('線要素を検索', { exact: true }).press('Enter')
  await expect(picker(page)).toHaveCount(0); await expect(format(page).locator('.route-item')).toHaveCount(2)
  await format(page).getByRole('button', { name: '線要素を追加', exact: true }).click()
  await format(page).getByText('経路構成', { exact: true }).click()
  await expect(picker(page)).toHaveCount(0)
  const input = format(page).getByLabel('EM-CE 5.5sq-3Cの条数', { exact: true })
  await input.fill('99'); await input.press('Enter')
  await expect(format(page).getByRole('button', { name: 'EM-CE 5.5sq-3Cの条数を増やす', exact: true })).toBeDisabled()
  await input.fill('0'); await input.press('Enter'); await expect(input).toHaveValue('99')
  await input.fill('2'); await format(page).getByText('経路構成', { exact: true }).click(); await expect(input).toHaveValue('2')
  await input.focus(); await input.hover(); await page.mouse.wheel(0, -100)
  await expect(input).toHaveValue('2'); expect((await routes(page))[0].count).toBe(2)
  await format(page).getByText('経路構成', { exact: true }).click()
  await page.keyboard.press('Control+z'); await selectRoute(page); await expect(input).toHaveValue('99')
  await expect(format(page).locator('.route-item-added')).toHaveCount(0)
})

test('拾いバーからの追加、11項目の上限と収まらない札の省略', async ({ page }) => {
  await setup(page)
  await page.getByRole('button', { name: '拾いバーで線要素を追加', exact: true }).click()
  await expect(picker(page).getByLabel('線要素を検索', { exact: true })).toBeFocused()
  await picker(page).getByLabel('線要素を検索', { exact: true }).fill('iv')
  await picker(page).locator('section').filter({ has: page.getByRole('heading', { name: 'この PDF の項目', exact: true }) }).getByRole('button', { name: 'IV 5.5sq', exact: true }).click()
  await expect(picker(page)).toHaveCount(0)
  await expect(format(page).locator('.route-item')).toHaveCount(2)
  for (let i = 0; i < 9; i++) await addFixture(page, 'L' + i, '', '追加線' + i)
  await selectRoute(page)
  await addLine(page, 'PF22', 'PF22')
  for (let i = 0; i < 8; i++) await addLine(page, '追加線' + i, 'L' + i)
  await expect(format(page).getByText('11種類・11条', { exact: true })).toBeVisible()
  await expect(format(page).locator('.route-item')).toHaveCount(11)
  await format(page).getByRole('button', { name: '線要素を追加', exact: true }).click()
  await expect(picker(page).getByRole('status')).toHaveText('これ以上足せません（最大 11 項目）')
  await picker(page).getByLabel('線要素を検索', { exact: true }).fill('追加線8')
  await expect(picker(page).getByRole('button', { name: 'L8', exact: true }).first()).toBeDisabled()
  await page.keyboard.press('Escape')
  await expect(page.locator('.pickup-route-more')).toContainText('ほか ')
  expect(await page.locator('.pickup-route-row').evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true)
})

test('別のPDFに構成の項目を作り、同じ項目の再選択では雛形を保つ', async ({ page }) => {
  await setup(page)
  await addLine(page, 'iv', 'IV 5.5sq')
  await addLine(page, 'pf2', 'PF28', true)
  await format(page).getByLabel('PF28の範囲', { exact: true }).selectOption('rise')
  await format(page).getByRole('button', { name: 'よく使う構成', exact: true }).click()
  const sets = page.getByRole('dialog', { name: 'よく使う構成', exact: true })
  await sets.getByLabel('構成の名前', { exact: true }).fill('別PDF幹線')
  await sets.getByRole('button', { name: '登録', exact: true }).click()
  await page.keyboard.press('Escape')
  await open(page, blankPdf())
  await panel(page).getByRole('button', { name: '拾う', exact: true }).click()
  await panel(page).getByRole('region', { name: 'よく使う構成', exact: true }).getByRole('button', { name: '別PDF幹線', exact: true }).click()
  await expect(panel(page).locator('.fixture-row-code')).toHaveCount(3)
  await row(page, 'EM-CE 5.5sq-3C', 'ケーブル').click()
  await expect(page.locator('.pickup-template')).toContainText('構成: 別PDF幹線')
  await draw(page, 220)
  await expect(format(page).locator('.route-item')).toHaveCount(3)
  await expect(format(page).getByLabel('PF28の範囲', { exact: true })).toHaveValue('rise')
  // Choosing another item clears the in-memory template.
  await row(page, 'IV 5.5sq', '接地線').click()
  await expect(page.locator('.pickup-template')).toHaveCount(0)
  await draw(page, 300)
  expect((await routes(page))[1].extra).toBeUndefined()
  const doc = new mupdf.PDFDocument(new Uint8Array(await saveBytes(page)))
  try {
    const all = readCountFixtures(doc)
    const appearances = all.map(f => JSON.stringify([f.style.color, f.line?.dash, f.line?.width]))
    expect(new Set(appearances).size).toBe(3)
    expect(listAnnotations(doc, 0)[0].contents).toContain('IV 5.5sq')
    expect(listAnnotations(doc, 0)[0].contents).not.toContain((await routes(page))[0].extra![0].itemId)
  } finally { doc.destroy() }
})
